"""Explainable berth pressure scoring for PortFlow.

The baseline score is deliberately simple and transparent:

    score = 100 * (1 - (0.40 * incoming_pressure
                         + 0.30 * occupancy_pressure
                         + 0.30 * yard_pressure))

All pressure inputs are clipped to ``[0, 1]``. A higher score means that the
berth has more room to absorb incoming work. This is a heuristic baseline for
testing and operations dashboards, not an ML prediction.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Mapping, Sequence

INCOMING_WEIGHT = 0.40
OCCUPANCY_WEIGHT = 0.30
YARD_WEIGHT = 0.30


def _number(value: Any, field: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError) as error:
        raise ValueError(f"{field} must be numeric") from error


def _clip(value: float) -> float:
    return min(1.0, max(0.0, value))


def _parse_time(value: Any, field: str) -> datetime:
    try:
        return datetime.fromisoformat(str(value))
    except ValueError as error:
        raise ValueError(f"{field} must be an ISO-8601 timestamp") from error


def _yard_fill(yard_zones: Sequence[Mapping[str, Any]]) -> float:
    if not yard_zones:
        raise ValueError("yard_zones must not be empty")
    capacities = [_number(zone["capacity_teu"], "capacity_teu") for zone in yard_zones]
    fills = [_number(zone["current_fill_pct"], "current_fill_pct") / 100 for zone in yard_zones]
    if any(capacity <= 0 for capacity in capacities):
        raise ValueError("yard zone capacities must be greater than zero")
    return _clip(sum(capacity * fill for capacity, fill in zip(capacities, fills)) / sum(capacities))


def _berth_metrics(
    berth: Mapping[str, Any],
    vessels: Sequence[Mapping[str, Any]],
    yard_pressure: float,
    as_of: datetime,
    horizon_hours: int,
) -> dict[str, Any]:
    berth_id = str(berth["berth_id"])
    incoming_vessels = [
        vessel
        for vessel in vessels
        if str(vessel.get("assigned_berth_id")) == berth_id
        and as_of <= _parse_time(vessel["eta"], "eta") <= as_of + timedelta(hours=horizon_hours)
    ]
    occupied_vessels = [
        vessel
        for vessel in vessels
        if str(vessel.get("assigned_berth_id")) == berth_id
        and _parse_time(vessel["eta"], "eta") <= as_of < _parse_time(vessel["etd"], "etd")
    ]
    incoming_teu = sum(_number(vessel["teu_capacity"], "teu_capacity") for vessel in incoming_vessels)
    crane_count = _number(berth["assigned_crane_count"], "assigned_crane_count")
    if crane_count <= 0:
        raise ValueError("assigned_crane_count must be greater than zero")

    # 2,000 TEU per crane over the planning horizon is a moderate workload.
    incoming_pressure = _clip(incoming_teu / (crane_count * 2000))
    # More than one active vessel is treated as fully occupied.
    occupancy_pressure = _clip(len(occupied_vessels))
    pressure = (
        INCOMING_WEIGHT * incoming_pressure
        + OCCUPANCY_WEIGHT * occupancy_pressure
        + YARD_WEIGHT * yard_pressure
    )
    score = round(100 * (1 - pressure), 1)
    return {
        "berth_id": berth_id,
        "berth_name": berth.get("berth_name", berth_id),
        "score": score,
        "incoming_vessel_count": len(incoming_vessels),
        "incoming_teu": incoming_teu,
        "incoming_pressure": round(incoming_pressure, 3),
        "occupied_vessel_count": len(occupied_vessels),
        "occupancy_pressure": round(occupancy_pressure, 3),
        "yard_fill_pressure": round(yard_pressure, 3),
    }


def score_berths(
    berths: Sequence[Mapping[str, Any]],
    vessels: Sequence[Mapping[str, Any]],
    yard_zones: Sequence[Mapping[str, Any]],
    *,
    as_of: datetime | None = None,
    horizon_hours: int = 24,
) -> list[dict[str, Any]]:
    """Return explainable 0–100 scores for every berth.

    ``vessels`` should contain the synthetic vessel fields generated by
    :mod:`src.data.generate_data`. ``as_of`` defaults to the first vessel ETA,
    which makes generated-data smoke tests deterministic.
    """
    if not berths:
        raise ValueError("berths must not be empty")
    if horizon_hours <= 0:
        raise ValueError("horizon_hours must be greater than zero")
    if as_of is None:
        if not vessels:
            raise ValueError("as_of is required when vessels is empty")
        as_of = min(_parse_time(vessel["eta"], "eta") for vessel in vessels)
    yard_pressure = _yard_fill(yard_zones)
    return sorted(
        (
            _berth_metrics(berth, vessels, yard_pressure, as_of, horizon_hours)
            for berth in berths
        ),
        key=lambda result: (-result["score"], result["berth_id"]),
    )
